export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_PRICING = 'SET_CURRENT_PRICING';
export const SET_CURRENT_SETTING = 'SET_CURRENT_SETTING';
export const UPDATE_CURRENT_SETTING = 'SET_CURRENT_SETTING';
export const LOGOUT = 'LOGOUT';